extend: '../openml_shared.yml'

problems:
  p0:
    class: 'LogisticRegressionOpenML'
    module: 'openml_problem'
    task_id: 6  # letter

plot:
  title: 'OpenML Letter Dataset Logistic Regression'
  time_column: 'times_finished'
  value_column: 'losses'
  bigger_is_better: True
