num_hb_runs: 15
num_runs: 256

problems:
  - name: 'Branin'
    label: 'p1'
    pow_z1: 1.
    pow_z2: 1.
    pow_z3: 1.
    deviation: 'boca'
    deviation_kwargs:
       bz: 0.05
       cz: 0.05
       tz: 0.05

strategies:
  - name: 'full'
    label: 's0'
    num_fidelities: 3
  - name: 'proptobudget'
    label: 's1'
    use_fidelity: [True, False, False]
  - name: 'proptobudget'
    label: 's2'
    use_fidelity: [False, True, False]
  - name: 'proptobudget'
    label: 's3'
    use_fidelity: [False, False, True]
  - name: 'proptobudget'
    label: 's4'
    use_fidelity: [True, True, True]
  - name: 'proptocost'
    label: 's5'
    problem: 'p1'
    num_fidelities: 3
    fallback: false

runs:
  - name: 'RandomSearch'
    problem: 'p1'
    strategy: 's0'
  - name: 'HyperBand'
    problem: 'p1'
    strategy: 's1'
  - name: 'HyperBand'
    problem: 'p1'
    strategy: 's2'
  - name: 'HyperBand'
    problem: 'p1'
    strategy: 's3'
  - name: 'HyperBand'
    problem: 'p1'
    strategy: 's4'
  - name: 'HyperBand'
    problem: 'p1'
    strategy: 's5'
