num_hb_runs: 15
num_runs: 3
extend: '../shared.yml'
problems:
  p1:
    class: 'Branin'
    module: 'branin'
    pow_z1: 1.
    pow_z2: 1.
    pow_z3: 1.
    deviation: 'boca'
    deviation_kwargs:
       bz: 0.05
       cz: 0.05
       tz: 0.05


runs:
  - optimizer: 'RandomSearch'
    problem: 'p1'
    strategy: 's0'
  - optimizer: 'HyperBand'
    problem: 'p1'
    strategy: 's1'
  - optimizer: 'HyperBand'
    problem: 'p1'
    strategy: 's2'
  - optimizer: 'HyperBand'
    problem: 'p1'
    strategy: 's3'
  - optimizer: 'HyperBand'
    problem: 'p1'
    strategy: 's4'
  - optimizer: 'HyperBand'
    problem: 'p1'
    strategy: 's5'
  - optimizer: 'HyperBand'
    problem: 'p1'
    strategy: 's6'
  - optimizer: 'HyperBand'
    problem: 'p1'
    strategy: 's7'
  - optimizer: 'HyperBand'
    problem: 'p1'
    strategy: 's8'
