num_hb_runs: 15
num_runs: 64

problems:
  p0:
    class: 'OpenmlGB'
    task_id: 3913
  p1:
    class: 'OpenmlRF'
    task_id: 3913

strategies:
  full:
    class: 'full'
    num_fidelities: 3
  pb:
    class: 'proptobudget'
    use_fidelity: [True, True, True]
  pc:
    class: 'proptocost'
    use_fidelity: [True, True, True]

runs:
  - optimizer: 'RandomSearch'
    problem: 'p0'
    strategy: 'rs'
  - optimizer: 'HyperBand'
    problem: 'p0'
    strategy: 's1'
  - optimizer: 'HyperBand'
    problem: 'p0'
    strategy: 's2'
  - optimizer: 'HyperBand'
    problem: 'p0'
    strategy: 's3'
  - optimizer: 'HyperBand'
    problem: 'p0'
    strategy: 's4'
  - optimizer: 'HyperBand'
    problem: 'p0'
    strategy: 's5'
  - optimizer: 'HyperBand'
    problem: 'p0'
    strategy: 's6'
  - optimizer: 'HyperBand'
    problem: 'p0'
    strategy: 's7'
  - optimizer: 'HyperBand'
    problem: 'p0'
    strategy: 's8'
