extend: '../openml_shared.yml'

problems:
  p0:
    class: 'OpenMLGB'
    module: 'openml_problem'
    task_id: 9952 # phoneme

plot:
  title: 'OpenML Phoneme Dataset GadientBoostedTrees'
  time_column: 'times_finished'
  value_column: 'losses'
  bigger_is_better: True
