num_hb_runs: 25
num_runs: 10

runs:
  - name: 'RandomSearch'
  - name: 'HyperBand'
    z1: True
    z1_pow: 3.
    z2_pow: 2.
    z3_pow: 1.
    bz: 0.05
    cz: 0.05
    tz: 0.05
  - name: 'HyperBand'
    z2: True
    z1_pow: 3.
    z2_pow: 2.
    z3_pow: 1.
    bz: 0.05
    cz: 0.05
    tz: 0.05
  - name: 'HyperBand'
    z3: True
    z1_pow: 3.
    z2_pow: 2.
    z3_pow: 1.
    bz: 0.05
    cz: 0.05
    tz: 0.05
  - name: 'HyperBand'
    z1: True
    z2: True
    z3: True
    z1_pow: 3.
    z2_pow: 2.
    z3_pow: 1.
    bz: 0.05
    cz: 0.05
    tz: 0.05
