extend: '../openml_shared.yml'
num_hb_runs: 15
num_runs: 128

problems:
  p0:
    class: 'OpenMLRF'
    module: 'openml_problem'
    task_id: 9952 # phoneme

plot:
  title: 'OpenML Phoneme Dataset Random Forest'
  time_column: 'times_finished'
  value_column: 'losses'
  bigger_is_better: True
