num_hb_runs: 25
num_runs: 10

runs:
  - name: 'RandomSearch'
  - name: 'HyperBand'
    z1: True
    bz: 0.01
    cz: 0.05
    tz: 0.1
  - name: 'HyperBand'
    z2: True
    bz: 0.01
    cz: 0.05
    tz: 0.1
  - name: 'HyperBand'
    z3: True
    bz: 0.01
    cz: 0.05
    tz: 0.1
  - name: 'HyperBand'
    z1: True
    z2: True
    z3: True
    bz: 0.01
    cz: 0.05
    tz: 0.1
