num_hb_runs: 10
num_runs: 5

problems:
    - name: 'Branin'
      label: 'b'
strategies:
    - name: 'full'
      label: 'f'
      num_fidelities: 3
runs:
  - name: 'RandomSearch'
    problem: 'b'
    strategy: 'f'
  - name: 'HyperBand'
    problem: 'b'
    strategy: 'f'

